### DISCUSSION TITLE
Palette Color

### DISCUSSION THREAD

**Discussion by TheOxymoron** [razonyang/hugo-theme-bootstrap#208] [Q&A] [answered]
Is it possible to use custom colors in the palette? 
For example to override the value of the palette "red" with some custom color?

**Comment by razonyang** [comment, marked as answer]
This can be overridden by adding the following custom CSS:

```css
.palette-red {
    --hbs-primary: #d32f2f;
    --hbs-primary-light: #ff6659;
}
```

The `primary` and `primary-light` color will be used in light and dark mode respectively.

**Reply by razonyang** [reply]
FYI, the new UI(#215) redesigns theming system, you'll need to add the following custom CSS in new UI:

```css
[data-palette=red] {
    --hbs-primary: #d32f2f;
    --hbs-primary-light: #ff6659;
    --hbs-on-primary: #fff;
}
```
