### DISCUSSION TITLE
Archive count

### DISCUSSION THREAD

**Discussion by UK-GT** [razonyang/hugo-theme-bootstrap#246] [Q&A] [answered]
can I change Archive ul tag  to ol  for counting?

**Comment by razonyang** [comment, marked as answer]
It can be solved by appending the following style to the **assets/css/custom.css**.

```css
.archive-posts {
  list-style: decimal;
  padding-left: 1.25rem;
}
```
