### DISCUSSION TITLE
New Language

### DISCUSSION THREAD

**Discussion by Ljukic12** [razonyang/hugo-theme-bootstrap#278] [Q&A] [answered]
Hi! I'm a newbie in Hugo and in web development but sooner or later I've to start!
I'm looking around how to create a new language folder instead the existing ones, such as Italian.
Someone can help me? Thanks!

**Comment by razonyang** [comment, marked as answer]
> Assumed that you followed the [installation guide](https://github.com/razonyang/hugo-theme-bootstrap#installation).

I recommend copying the `content/en` for getting to start, because this theme requires some predefined pages for turning their features on, such as search, archive, offline etc.

```shell
cp -r content/en content/it
```

And then put the following configurations in `config/_default/languages.toml`.

```toml
[it]
  languageName = "Italian"
  weight = 2
  contentDir = "content/it"
  [it.params] # override the default parameters
    dateFormat = "02-01-2006"
    description = "Site description"
    keywords = "Site keywords"
    # ...
```

Now, you can access your new language page after restarting hugo server or rebuilding your site. http://localhost:1313/it/ by default.

The last step is that to remove the needless posts, and create a new post.

```
rm -r content/it/posts/*
hugo new content/it/posts/first-post.md
```

> Please make sure that the `content/it/posts` exists, otherwise, hugo generates and saves the file as `content/en/posts/first-post.md`.

> Note: there seems a bug of 0.89.4 gohugoio/hugo#9204, I would suggest to use 0.88.1.

What is next?

- Read the docs on https://gohugo.io/getting-started/.
- Tweak your site's configuration: https://github.com/razonyang/hugo-theme-bootstrap#configuration
- Please feel free to share your feedback and ideas, or ask questions.
