### DISCUSSION TITLE
Ordering taxonomy widgets in the sidebar

### DISCUSSION THREAD

**Discussion by sagarbehere** [razonyang/hugo-theme-bootstrap#319] [Q&A] [answered]
The existing sidebar shows the taxonomy widgets ordered as `Categories`, `Series`, and `Tags` in that sequence. I'd like to change the order to `Tags`, `Categories`, and `Series` i.e. first the Tags should appear, followed by Categories, and the Series should be at the very bottom.

How to get that? I looked at the `layouts/partials/sidebar/taxonomies.html` file and it seems that the ordering is somehow coming from the first line `{{- range $key, $value := .Site.Taxonomies -}}`. It seems that this returns the `Categories` key first, which then becomes the first displayed widget, followed by Series and then Tags. But I couldn't figure out how to tweak this to my desired sequence.

**Comment by razonyang** [comment]
I didn't find an ideal solution. I pushed a new commit e59069cba2c0296c36db625b7a1987d71636d490 for it.
Now you can set the order of taxonomies by CSS(`assets/css/custom.css`).

```css
.tags-taxonomies {
    order: 1;
}

.categories-taxonomies {
    order: 2;
}

.series-taxonomies {
    order: 3;
}
```
