### DISCUSSION TITLE
Docs Layout - how to achieve it

### DISCUSSION THREAD

**Discussion by sardarms** [razonyang/hugo-theme-bootstrap#425] [Q&A] [answered]
Hi, thank you for the awesome theme. I am new to Hugo and cannot figure out how to have the 'docs' layout. 

My question is what I need to do to have the 'docs' layout for certain sections of my site. 

I have put the files as you described in the [documentation](https://hbs.razonyang.com/en/docs/layouts/docs/) with an _index.md file in the root folder. But does not do show the content in the 'docs' layout.  

Then I have tried the following code in the frontmatter (in _index.md file) without success: 

```
---
title: Group 1
url: /group
cascade:
  postDate: false
  readingtime: false
  layout: docs
---
```
Can you guys please help me? 

Also, as a suggestion, can you please elaborate the relevant [documentation](https://hbs.razonyang.com/en/docs/layouts/docs/)? I find the documentation is not very elaborative for the novice.
