### DISCUSSION TITLE
about series

### DISCUSSION THREAD

**Discussion by luqicoder** [razonyang/hugo-theme-bootstrap#436] [Ideas]
![image](https://user-images.githubusercontent.com/49476849/157583233-a861b4ec-c278-4cb6-8cfd-5bb350e7f5ad.png)
当我点击专栏分类下**阅读**文章时，上面的导航栏会跳转到文章所在目录！
![image](https://user-images.githubusercontent.com/49476849/157583339-ef7a25cd-9d67-4e46-80fb-fd6bbe739f70.png)
能不能设置让我点击阅读的文章仍然处在专栏分类下面！
由：**主页/专栏/文档/**
变成：**主页/专栏/文档/快速入门**
而不是：**主页/文章/快速入门**

**Comment by luqicoder** [comment]
还有分类与标签！

**Comment by razonyang** [comment]
这应该不可行，毕竟静态网页，不会记住你从哪个页面过来的。虽然可以通过 JS 来动态修改，不过意义不大。

**Comment by luqicoder** [comment]
![image](https://user-images.githubusercontent.com/49476849/157621946-9bca24c8-2f43-4e99-b0b6-c8c21de7967a.png)
我在content中新增一个talks文件夹了，里面有三个子目录movies，music，books。现在music音乐目录下有一篇文章！
![image](https://user-images.githubusercontent.com/49476849/157622310-06ad3daf-2325-4fe2-806f-c5155c4f31e4.png)
但是我在导航栏中的talks看到显示是空的，只能在主页才能显示，我不清楚这是为什么？而且talks也没有显示中文

![image](https://user-images.githubusercontent.com/49476849/157622602-b66b5f3b-0f5c-4931-8bb3-8c2fde164c75.png)
![image](https://user-images.githubusercontent.com/49476849/157623308-96f18a4b-ceac-4dab-8fc8-8201015710cc.png)

**Comment by razonyang** [comment]
你的 `content/talks/_index.md` 的内容是什么？怎么感觉像指定了分类的布局。

**Comment by luqicoder** [comment]
只写了标题
title = "杂谈"

**Comment by razonyang** [comment]
我看了下你的仓库，你混用了 Section 和 Taxonomy，把 `config.toml` 中的 `talks` 删掉就好了：

```toml
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  talks =  "talks" # 删除这行
```

**Reply by luqicoder** [reply]
> 我看了下你的仓库，你混用了 Section 和 Taxonomy，把 `config.toml` 中的 `talks` 删掉就好了：
> 
> ```toml
> [taxonomies]
>   category = "categories"
>   series = "series"
>   tag = "tags"
>   talks =  "talks" # 删除这行
> ```

好的，感谢作者。我碰到了另一个问题。我构造github action用于上传文件。bulid hugo出现了下面的提示
![image](https://user-images.githubusercontent.com/49476849/157663708-65e05550-714a-423c-a69b-281a765efcb9.png)

**Reply by luqicoder** [reply]
麻烦你看下我github仓库中的actions，我暂时不清楚什么问题

**Reply by razonyang** [reply]
大概率是因为没有更新 submodule，你在 workflow 中 checkout 那一步修改下试试。
https://github.com/actions/checkout

```yaml
- uses: actions/checkout@master
  with:
    submodules: 'recursive'
```

**Reply by luqicoder** [reply]
更改之后出现了这个问题
![image](https://user-images.githubusercontent.com/49476849/157670000-fa6f2e07-eeeb-41a8-9690-64559c519465.png)
然后我引入npm，解决了。新的问题是：github页面没能正确渲染
```
- name: Checkout
        uses: actions/checkout@master
        with:
            submodules: 'recursive'
        # Start ssh-agent but set it to use the same ssh_auth_sock value.
        # The agent will be running in all steps after this, so it
        # should be one of the first.
      - name: setup npm
        uses: actions/setup-node@v2
        with:
            node-version: '14'
      - name: install npm
        run: npm install
      - name: setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: 'latest'
            extended: true
```
但是我的[https://luqicoder.github.io](https://luqicoder.github.io)没能正确渲染
