### DISCUSSION TITLE
Fixed sidebar for posts

### DISCUSSION THREAD

**Discussion by LITUATUI** [razonyang/hugo-theme-bootstrap#461] [Q&A] [answered]
Hi guys.

What's the best way to make the sidebar for posts fixed?

Thanks!

**Comment by razonyang** [comment, marked as answer]
There are two options to do that.

## 1. Stick one widget on the sidebar

See also #404.

## 2. Stick the whole sidebar

Append the following CSS to `assets/main/scss/_custom.scss`.

```scss
.sidebar {
    @include media-breakpoint-up(lg) {
        height: calc(100vh - 84px);
        overflow: scroll;
        position: sticky;
        top: 84px;
    }
}
```
