### DISCUSSION TITLE
Menu customisation

### DISCUSSION THREAD

**Discussion by Mecanik** [razonyang/hugo-theme-bootstrap#533] [Q&A] [answered]
Hello,

Is there a way to alter the main menu and remove Series, Archives, Categories, Tags? More specifically I would like to put them under a menu called "Blog" or something and add other items instead.

Had a play around with the config but did not succeed and I do not want to alter the hugo module.

Many thanks!

**Comment by razonyang** [comment, marked as answer]
Yes. Let's take `Tags` as an example:

1. Create a parent menu first:

```toml
// config/_default/menu.toml

[[main]]
  name = "Blog"
  identifier = "blog"
```

2. Connect the two menus with the `parent` directive.

```toml
// content/tags/index.md

[menu.main]
  weight = 30
  pre = '<i class="fas fa-fw fa-tags"></i>'
  parent = 'blog'
```

The `parent` should be equal to the `identifier` we defined above.

Further reading: [Menu](https://hbs.razonyang.com/en/docs/menu/).
