### DISCUSSION TITLE
Move widgets sidebar after post container

### DISCUSSION THREAD

**Discussion by iamgiannisx** [razonyang/hugo-theme-bootstrap#687] [Ideas]
Is it possible to move widgets sidebar container after the post container at mobile view.

I think this is a better approach in terms of UX.

**Comment by razonyang** [comment]
The main purpose about placing the sidebar widgets above content on small screens is that the TOC should be present before content.

But you're able to change this behavior via CSS.

```scss
// assets/main/scss/_custom.scss
.sidebar {
    order: 5;
}
```
