### ISSUE TITLE
How to reduce the svg icon size in the Author part?

### ISSUE THREAD

**Issue by martijnvandenboom** [razonyang/hugo-theme-bootstrap#1118]
Dear reader,

Attn: Razon Yang

Now the Author part with me looks like this:
<img width="408" alt="Image" src="https://github.com/user-attachments/assets/cd45d678-2851-4d0b-b252-54823e67610a" />

I tried with the "Developers Tools" inside Google Chrome Browser to find the css tag that would be holding a size setting.
But I failed to find it.

Are you able to give me some hints / tips on how I can reduce the size of the svg icons in the Author part?
Perhaps I would also like to reduce the padding or margin. Are those settings in the same CSS tag?

Best regards,
Martijn

**Comment by razonyang** [comment]
I believe there isn't such configuration, please using custom css/scss to tweak the size

**Comment by razonyang** [comment]
For example,

```scss
// assets/main/scss/_custom.scss
.profile {
    .social-link
        font-size: .75rem;
    }
}
```
