### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by eskopp** [razonyang/hugo-theme-bootstrap#1135]
### Prerequisites

- [x] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [x] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [x] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

Hi guys,
I have a similar problem as @martijnvandenboom in #1115. The basic problem seems to be the different versions of NPM. At least that's what I think at the moment. Interestingly enough, I can run it in a test environment (Debian 12 with NPM (9.2) and nodejs (v18.19.1). I know myself that this is too old, but it's only a WSL2 ^^. Anyway, it runs solidly. But if I put it into a workflow as described below I also get the error. Even if you take the old packages from the original git you get the problem. A Go, NPM, Hugo cache can be excluded here. At the moment I'm a bit desperate as to what I'm doing wrong. I'll attach everything below. Maybe you can help me. Thanks :)

## Build Skript
```yaml
build:
  stage: build
  image: archlinux:latest

  before_script:
    # Systempakete
    - pacman -Syu --noconfirm
    - pacman -S --noconfirm git go nodejs npm python dos2unix wget ca-certificates tar

    # Hugo Extended installieren
    - wget https://github.com/gohugoio/hugo/releases/download/v0.145.0/hugo_extended_0.145.0_Linux-64bit.tar.gz -O hugo.tar.gz
    - tar -xzf hugo.tar.gz hugo
    - mv hugo /usr/local/bin/
    - hugo version

    # Node & npm check
    - node -v
    - npm -v

  script:
    - echo "Running Hugo build..."
    - hugo mod get
    - hugo mod get github.com/razonyang/hugo-theme-bootstrap
    - npm install
    - npm audit fix || true
    - hugo --gc --minify --enableGitInfo

  artifacts:
    paths:
      - public/
    expire_in: 1 week
```

## Related errors or issues
#1116 and #1115 

## GitLab Repo
[https://gitlab.erik-skopp.de/erikskopp/website](https://gitlab.erik-skopp.de/erikskopp/website)
## Error Log 
```yml
$ hugo --gc --minify --enableGitInfo
Start building sites … 
hugo v0.145.0-666444f0a52132f9fec9f71cf25b441cc6a4f355+extended linux/amd64 BuildDate=2025-02-26T15:41:25Z VendorInfo=gohugoio
Total in 3698 ms
Error: error building site: POSTCSS: failed to transform "assets/main/bundle.min.css" (text/css): TypeError: require(...) is not a function
    at Object.<anonymous> (/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/razonyang/hugo-theme-bootstrap@v1.13.1/purgecss.config.js:8:56)
    at Module._compile (node:internal/modules/cjs/loader:1734:14)
    at Object..js (node:internal/modules/cjs/loader:1899:10)
    at Module.load (node:internal/modules/cjs/loader:1469:32)
    at Function._load (node:internal/modules/cjs/loader:1286:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1491:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/razonyang/hugo-theme-bootstrap@v1.13.1/postcss.config.js:8:10)
```

## Complete Log: 
[https://nbg1.your-objectstorage.com/eskopp-gitlab/19/58/19581e27de7ced00ff1ce50b2047e7a567c76b1cbaebabe5ef03f7c3017bb5b7/2025_04_07/436/574/job.log?response-content-type=text%2Fplain%3B%20charset%3Dutf-8&response-content-disposition=inline&X-Amz-Expires=600&X-Amz-Date=20250407T102032Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=K4A1GHWLQ6VKXDZYH11L%2F20250407%2Fnbg1%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=d0ea2087e943dff6c8eaa37765e5634d27316201fb396d1eec0081552266ba30](https://nbg1.your-objectstorage.com/eskopp-gitlab/19/58/19581e27de7ced00ff1ce50b2047e7a567c76b1cbaebabe5ef03f7c3017bb5b7/2025_04_07/436/574/job.log?response-content-type=text%2Fplain%3B%20charset%3Dutf-8&response-content-disposition=inline&X-Amz-Expires=600&X-Amz-Date=20250407T102032Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=K4A1GHWLQ6VKXDZYH11L%2F20250407%2Fnbg1%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=d0ea2087e943dff6c8eaa37765e5634d27316201fb396d1eec0081552266ba30)

### Steps to reproduce

1. create a new Hugo project.
2. load the theme as a module (see: https://gitlab.erik-skopp.de/erikskopp/website/-/blob/main/config/_default/config.yaml?ref_type=heads#L34
3. create a go.mod and embed the theme. (https://gitlab.erik-skopp.de/erikskopp/website/-/blob/main/go.mod?ref_type=heads#L5)
4. install the node (npm) dependencies and then hugo server.

### Expected behavior

Hugo Theme works ? ^^

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of theme are you using?

latest

### What version of Hugo are you using?

v0.145.0-666444f0a52132f9fec9f71cf25b441cc6a4f355+extended

### What version of Node.js are you using?

v23.9.0

### What version of Git are you using?

latest
