### ISSUE TITLE
Mathematical Formula

### ISSUE THREAD

**Issue by MarcinKlejna** [razonyang/hugo-theme-bootstrap#174]
Is it possible to add support for math formulas https://katex.org/?
Here is a list of [ TeX functions supported by KaTeX ](https://katex.org/docs/supported.html)

**Comment by MarcinKlejna** [comment]
Ah, my error works, I don't know why the formulas in the line do not work for the `$` / `$` marker but `//(` `//)` e.g.

`$\LaTeX$` does not work
`\\(\LaTeX\\)` works

**Comment by razonyang** [comment]
I have no much experience about using Katex, but I'm sure it's a configuration problem about delimiters. The Katex configuration is hard-coded so far, I'll make these parameters configurable.

**Comment by razonyang** [comment]
@MarcinKlejna I created a PR #175, I'm looking forward to your feedback before merging it.

For testing locally, you will be needed to checkout the branch `feature-katex`:

```shell
cd themes/hugo-theme-bootstrap
git fetch
git checkout feature-katex
```

and then add the `katex` parameter:

```toml
[katex]
  [[katex.delimiters]]
    left = "$$"
    right = "$$"
    display = true
  [[katex.delimiters]]
    left = "$"
    right = "$"
    display = false
  [[katex.delimiters]]
    left = "\\("
    right = "\\)"
    display = false
  [[katex.delimiters]]
    left = "\\begin{equation}"
    right = "\\end{equation}"
    display = true
  [[katex.delimiters]]
    left = "\\begin{align}"
    right = "\\end{align}"
    display = true
  [[katex.delimiters]]
    left = "\\begin{alignat}"
    right = "\\end{alignat}"
    display = true
  [[katex.delimiters]]
    left = "\\begin{gather}"
    right = "\\end{gather}"
    display = true
  [[katex.delimiters]]
    left = "\\begin{CD}"
    right = "\\end{CD}"
    display = true
  [[katex.delimiters]]
    left = "\\["
    right = "\\]"
    display = true
```

Katex options:

- https://katex.org/docs/options.html
- https://katex.org/docs/autorender.html
