### ISSUE TITLE
Code looks like a link and some links look like text

### ISSUE THREAD

**Issue by vmihailenco** [razonyang/hugo-theme-bootstrap#205]
![code-link](https://user-images.githubusercontent.com/290976/132982750-ab34028a-a939-4a23-9de3-8f45dd150ad3.png)

This can be easily fixed with some css, but would be nice to have a sensible default which looks more like >> `code` <<.

```css
code:not(.no-ln) {
  padding: .25rem .5rem;
  font-weight: 500;
  color: #4e6e8e;
  background-color: #f3f4f5;
  border-radius: 3px;
}
```

And some links look like text which can confusing too:

![related-posts](https://user-images.githubusercontent.com/290976/132982838-5577fc56-13ea-4901-b2fc-718b00a63ba0.png)

I would always use the same color for links and would made links more pronounce:

```css
a {
  font-weight: 500;
}
```

And thanks for your work!
