### ISSUE TITLE
Bootstrap and theme styling rule

### ISSUE THREAD

**Issue by vmihailenco** [razonyang/hugo-theme-bootstrap#218]
One of the reasons I like this theme is Bootstrap. It allows to use existing Bootstrap components without creating another CSS framework.

But then you also need to add some CSS for the theme and inevitably break/change Bootstrap CSS. Which is not nice because it is not Bootstrap any more.

I think we could minimize the damage by agreeing to not change global CSS rules, e.g. this is not okay

```css
h1,
h2,
h3,
h4,
h5 {
  margin: 1rem 0 1.5rem;
  clear: both;
}
```

And instead it should be:

```css
.header {}
.main {
  h1,
  h2,
  h3,
  h4,
  h5 {
    margin: 1rem 0 1.5rem;
    clear: both;
  }
}
.sidebar {}
.footer {}
```

That requires repeating some rules for different sections, but then we can change CSS for different sections without affecting other sections (and keep Bootstrap unaffected). What do you think?
