### ISSUE TITLE
Adding more icons to reward widget

### ISSUE THREAD

**Issue by yshalsager** [razonyang/hugo-theme-bootstrap#249]
**Is your feature request related to a problem? Please describe.**
This is a feature request. I would like to have more icons in reward widget for other payment methods such as PayPal, Payoneer, Patreon, liberapay, Flattr, etc.

![image](https://user-images.githubusercontent.com/17043808/139454134-5119f6d1-94c8-470f-9a2c-00e50d605bbe.png)

**Describe the solution you'd like**
Adding more icons is enough, since it's already possible to define reward methods in params file and adding new string in i18n directory like the following:

`config/_default/params.toml`:
```toml
[reward]
  paypal = "images/reward/paypal.png"
  liberapay = "images/reward/liberapay.png"
```

`i18n/en.toml`:
```toml
[paypal]
other = "PayPal"

[liberapay]
other= "LiberaPay"
```

**Describe alternatives you've considered**
None.

**Additional context**
Thanks for the awesome theme!
