### ISSUE TITLE
Font performance is somewhat different between Firefox and chrome browsers

### ISSUE THREAD

**Issue by unzybaryl** [razonyang/hugo-theme-bootstrap#286]
firefox:
![image](https://user-images.githubusercontent.com/83069411/144464055-f5b5e543-90a4-4d0e-ae24-264302324857.png)
chrome:
![image](https://user-images.githubusercontent.com/83069411/144464135-a0c094d9-88f5-4109-8066-362dd24e18a0.png)

**Comment by razonyang** [comment]
Are these screenshots from the same device/platform? We don't specify any font, that is, the `system-ui` will be used.

> `system-ui`: Glyphs are taken from the default user interface font on a given platform. Because typographic traditions vary widely across the world, this generic is provided for typefaces that don't map cleanly into the other generics. 
-- https://developer.mozilla.org/en-US/docs/Web/CSS/font-family

The `font-family` is defined as follows:

```CSS
body {
  font-family: var(--hbs-body-font-family);
}

:root {
  --hbs-body-font-family: var(--hbs-font-sans-serif);
  --hbs-font-sans-serif: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", "Liberation Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
}
```

You can import any web fonts([Google Fonts](https://fonts.google.com/)) by `customCSS` parameter or hooks, and then modify the  by overriding the CSS variables(`assets/css/custom.css`).
