### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by razonyang** [razonyang/hugo-theme-bootstrap#433]
**Is your feature request related to a problem? Please describe.**
Allow specifying the background image via a parameter.

**Describe the solution you'd like**

```toml
backgroundImage = ['/images/bg.png'] # Use the same image on light and dark modes.
backgroundImage = ['/images/bg-light.png', 'images/bg-dark.png'] # Use different images on light and dark modes.
```
