### ISSUE TITLE
Wrong URLs in docs/repo widget while using language custom contentDir

### ISSUE THREAD

**Issue by yshalsager** [razonyang/hugo-theme-bootstrap#475]
**Describe the bug**
If contentDir is configured for a language, URLs of viewing and editing the files in docs/repo widget will be wrong.

`config/_default/languages.toml`:
```toml
[ar]
  languageName = "العربية"
  languagedirection = 'rtl'
  weight = 2
  contentDir = "content/ar"
```

Wrong URL Example: `https://github.com/user/repo/blob/master/content/notes/books/xyz/index.md`
Correct URL Example: `https://github.com/user/repo/blob/master/content/ar/notes/books/xyz/index.md`

**Hugo version:** v0.93.2+extended linux/amd64 

**Theme version:** v0.72.0

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Brave Version 1.36.116 Chromium: 99.0.4844.74 (Official Build) (64-bit)
