### ISSUE TITLE
Heading is "expanded" when clicking/opening anchor

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#501]
**Describe the bug**
When you open an anchor via URL oder click on an anchor the heading is "expanded". You can see this in my blog because I added numbering for headings.

**To Reproduce**
A) Open a blog post with at least 1 heading. Click an anchor of a heading.
or
B) Open an anchor, for example https://blog.natenom.com/2022/04/aenderungen-im-blog/#neue-icons--octicons

**Expected behavior**
Do not expand the heading area.

**Screenshots**
The size of heading before expansion:
![image](https://user-images.githubusercontent.com/385995/162088088-de22c6fd-5add-4919-9e47-c2faaea0c9cd.png)

After clicking the anchor or opening via anchor
![image](https://user-images.githubusercontent.com/385995/162088105-d46e41fa-ab6a-400c-85ee-40ee4eaf1b9a.png)

**Hugo version:**
hugo v0.95.0+extended linux/amd64 BuildDate=2022-03-21T18:19:26Z VendorInfo=debian:0.95.0-1

**Theme version:**
69144efc9f264380f7a01e151e5ddbcee537cc6e (HEAD -> master, tag: v0.74.0, origin/master, origin/HEAD) fix(viewer): filter the linkable picture tags

**Comment by razonyang** [comment]
I think it's relative to your custom CSS. You need to change it as follows:

```scss
html {
    scroll-padding-top: 64px;
}

.post-content>h2::before, .post-content>.h2::before {
    content: counter(level2) " ";
    counter-increment: level2;
    display: inline;
}
```

The key points are the `scroll-padding-top` and `display: inline`.
