### ISSUE TITLE
Numberify Headings for TOC?

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#503]
**Describe the solution you'd like**
Add numbering for headings in ToC. (tried it myself, but it didn't work)

BTW: Just updated to the latest version. Thank you for adding this to your theme :)

**Comment by razonyang** [comment]
The TOC(`ul`) is different from headings(`h1-h6`).

```css
#TableOfContents ul, ol {
    list-style-type: decimal;
}
```

I'll create a new parameter called `post.tocStyleType` for doing that.
