### ISSUE TITLE
Build fails when news article has image uploaded to static/images/uploads

### ISSUE THREAD

**Issue by andresf91** [razonyang/hugo-theme-bootstrap#686]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

I couldn't find issues related to this.
I'm trying to integrate NetlifyCMS to this theme.
All images are uploaded to the same media library, in this case, static/images/uploads, instead of being uploaded to the article folder in content/news/{slug}/.

This is the error log in Netlify:

```
4:48:17 PM: Start building sites …
4:48:17 PM: hugo v0.97.3-078053a43d746a26aa3d48cf1ec7122ae78a9bb4+extended linux/amd64 BuildDate=2022-04-18T17:22:19Z VendorInfo=gohugoio
4:48:17 PM: WARN 2022/08/30 19:48:17 no such image can be found in page resources and the static folder: static/47
4:48:17 PM: WARNING: calling IsSet with unsupported type "string" (string) will always return false.
4:48:17 PM: WARNING: calling IsSet with unsupported type "string" (string) will always return false.
4:48:19 PM: Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:15:8: executing "_default/single.html" at <partial "head.html" .>: error calling partial: "/opt/build/cache/hugo_cache/modules/filecache/modules/pkg/mod/github.com/razonyang/hugo-theme-bootstrap@v1.0.0-alpha.8/layouts/partials/head.html:7:18": execute of template failed: template: partials/head.html:4:4: executing "partials/head.html" at <partial "head/meta" .>: error calling partial: execute of template failed: template: partials/head/meta.html:2:4: executing "partials/head/meta.html" at <partial "head/meta/social" .>: error calling partial: "/opt/build/cache/hugo_cache/modules/filecache/modules/pkg/mod/github.com/razonyang/hugo-theme-bootstrap@v1.0.0-alpha.8/layouts/partials/head/meta/social.html:7:18": execute of template failed: template: _internal/opengraph.html:7:18: executing "_internal/opengraph.html" at <.>: range can't iterate over /image
Total in 2617 ms
4:48:19 PM: ​
4:48:19 PM: ────────────────────────────────────────────────────────────────
4:48:19 PM:   "build.command" failed                                        
4:48:19 PM: ────────────────────────────────────────────────────────────────
4:48:19 PM: ​
4:48:19 PM:   Error message
4:48:19 PM:   Command failed with exit code 255: npm install && hugo --minify (https://ntl.fyi/exit-code-255)
4:48:19 PM: ​
4:48:19 PM:   Error location
4:48:19 PM:   In build.command from netlify.toml:
4:48:19 PM:   npm install && hugo --minify
4:48:19 PM: ​
4:48:19 PM:   Resolved config
4:48:19 PM:   build:
4:48:19 PM:     command: npm install && hugo --minify
4:48:19 PM:     commandOrigin: config
4:48:19 PM:     environment:
4:48:19 PM:       - NODE_VERSION
4:48:19 PM:       - HUGO_VERSION
4:48:19 PM:       - HUGO_ENABLEGITINFO
4:48:19 PM:       - HUGO_ENV
4:48:19 PM:     publish: /opt/build/repo/public
4:48:19 PM:     publishOrigin: config
4:48:19 PM:   headers:
4:48:20 PM:     - for: /*
      values:
        Referrer-Policy: strict-origin-when-cross-origin
        X-Content-Type-Options: nosniff
        X-Frame-Options: deny
        X-XSS-Protection: 1; mode=block
  headersOrigin: config
  redirects:
    - from: /:lang/*
      status: 404
      to: /:lang/404.html
    - from: /*
      status: 404
      to: /404.html
  redirectsOrigin: config
Caching artifacts
```

### Steps to reproduce

Upload image to static/images/uploads/photo.jpg

Create file in content/news/2022-08-30-prueba-con-imagen/index.md:

```
---
title: Test with a pic
date: 2022-08-30T19:46:44.479Z
featured: "false"
draft: "false"
toc: "false"
pinened: "true"
images: /images/uploads/photo.jpg
---
Test with a pic text
```

### Expected behavior

Build doesn't fail.
It displays a news article with an image.

### What operating system(s) are you seeing the problem on?

Linux

### What version of theme are you using?

  "name": "hugo-theme-bootstrap-skeleton",   "version": "0.1.0"

### What version of Hugo are you using?

0.97.3

### What version of Node.js are you using?

17.6.0

### Additional context

NetlifyCMS config.yml:

```
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
# REFERENCE: https://www.netlifycms.org/docs/configuration-options/
# This lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
site_url: https://netlifycms--cehceprueba.netlify.app # cambiar cuando se publique
display_url: https://netlifycms--cehceprueba.netlify.app/ # cambiar cuando se publique
locale: 'es'
# COLLECTIONS
collections:
  - name: "articulos" # Used in routes, e.g., /admin/collections/blog
    label: "Artículos" # Used in the UI
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}/index" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Título", name: "title", widget: "string", required: true}
      - {label: "Fecha de publicación", name: "date", widget: "datetime"}
      - {label: "¿Destacado?", name: "featured", widget: "select", options: ["true", "false"], default: "false"}
      - {label: "¿Borrador?", name: "draft", widget: "select", options: ["true", "false"], default: "false"}
      - {label: "¿Tabla de contenidos?", name: "toc", widget: "select", options: ["true", "false"], default: "false"}
      - {label: "¿Permanente?", name: "pinened", widget: "select", options: ["true", "false"], default: "false"}
      - label: "Imagen destacada"
        name: "images"
        widget: "image"
        choose_url: true
        media_library:
          config:
            multiple: true
      - {label: "Cuerpo del artículo", name: "body", widget: "markdown"}
```
